### ISSUE TITLE
how can i check if a field exists?

### ISSUE THREAD

**Issue by mkliu** [a8m/doqmentdb#30]
In mongo i could use $exists, what should I use here?

**Comment by a8m** [comment]
```js
users.find({$not: { field_name: { $type: 'undefind' }  } })
```
**Note**: you should use `v0.3.1` to support UDF, because [the older syntax has been deprecated](http://stackoverflow.com/questions/29278574/userdefined-function-is-not-working-any-more-in-document-db).
