### ISSUE TITLE
Schema with Array of Objects

### ISSUE THREAD

**Issue by harshithkashyap** [a8m/doqmentdb#37]
How do we specify an array of embedded documents in the schema?

Eg: In MongooseJS I'd specify as

``` javascript
var BlogSchema = new Schema({
    title: String,
    body: String,
    comments: [{
        commenter_id: String,
        comment: String
    }]
});

```

How do we embed the comments schema in blog schema in doqmentdb?

**Comment by YuryJefse** [comment]
I have the same question... -.-'

**Comment by markvivanco** [comment]
Can anyone answer this question or have figured it out?

**Comment by harshithkashyap** [comment]
@markvivanco We are now using MongooseJS since DocumentDB released support for using MongoDB drivers
